### ISSUE TITLE
Peer-to-peer-code-review

### ISSUE THREAD

**Issue by Laylo309** [Felipeg005/Portfolio#10]
- In the semantic HTML change name of div's

**Comment by zainsadaqat** [comment]
# Hello @Felipeg005  😃 

You did a great job 👏🏻 Both Figma design and website look identical and pixel perfect 👍🏻 . The code is clean and you followed the best practices. 

> However, you can make your code more SEO friendly if you use semantic tags like article, ul, li instead of div at some places. 🤙🏻

All the Best! 🥳
